In [15]:
import pandas as pd
from IPython.core.display_functions import display

# Load the given JSON dataset from GitHub
raw_url="delhi_metro_trips.json"
dmt_df = pd.read_json(raw_url)

display(dmt_df.info())

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[us]
 2   From_Station        10000 non-null  str
 3   To_Station          10000 non-null  str
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         9888 non-null   str
 9   Remarks             8246 non-null   str
dtypes: datetime64[us](1), float64(4), int64(1), str(4)
memory usage: 859.4 KB

None

In [16]:
display(dmt_df.describe())

,TripID,Date,Distance_km,Fare,Cost_per_passenger,Passengers
count,10000.000000,10000,10000.000000,10000.000000,10000.000000,9910.000000
mean,75119.461100,2023-07-01 16:59:22.560000,5.454417,104.386132,62.899180,20.017962
min,35.000000,2022-01-01 00:00:00,0.500000,10.010000,5.040000,5.000000
25%,38425.000000,2022-10-03 00:00:00,1.900000,56.802500,34.077500,17.000000
50%,74774.500000,2023-07-06 12:00:00,3.930000,104.540000,63.320000,20.000000
75%,112112.500000,2024-03-31 00:00:00,7.330000,150.745000,92.090000,23.000000
max,149984.000000,2024-12-30 00:00:00,45.690000,199.990000,120.000000,37.000000
std,42909.579425,NaN,5.026506,54.789233,33.298324,4.473702

In [17]:
display(dmt_df.head(100))

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,NaN,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
95,136207,2022-06-12,Rajouri Garden,Chandni Chowk,4.04,95.71,22.34,16.0,NaN,off-peak
96,22935,2023-11-08,Noida City Centre,Rajouri Garden,5.40,134.64,28.36,23.0,Tourist Card,festival
97,133891,2023-01-24,Noida City Centre,Punjabi Bagh,9.01,40.85,85.30,22.0,Tourist Card,off-peak
98,56198,2023-12-17,Kashmere Gate,Kirti Nagar,1.22,193.09,29.88,15.0,Single,off-peak
99,130665,2022-10-11,Jasola Vihar,Chandni Chowk,11.94,124.48,75.62,16.0,Single,NaN

In [18]:
#Remove leading/trailing spaces from the Station Names
dmt_df['From_Station']=dmt_df['From_Station'].str.strip()
dmt_df['To_Station']=dmt_df['To_Station'].str.strip()
display(dmt_df.info())

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[us]
 2   From_Station        10000 non-null  str
 3   To_Station          10000 non-null  str
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         9888 non-null   str
 9   Remarks             8246 non-null   str
dtypes: datetime64[us](1), float64(4), int64(1), str(4)
memory usage: 859.4 KB

None

In [19]:
# Standardize naming convensions in Station Names
dmt_df['From_Station']=dmt_df['From_Station'].str.title()
dmt_df['To_Station']=dmt_df['To_Station'].str.title()
display(dmt_df.info())

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[us]
 2   From_Station        10000 non-null  str
 3   To_Station          10000 non-null  str
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         9888 non-null   str
 9   Remarks             8246 non-null   str
dtypes: datetime64[us](1), float64(4), int64(1), str(4)
memory usage: 859.4 KB

None

In [21]:
# Handle missing values in Ticket Types and Remarks
dmt_df['Ticket_Type']=dmt_df['Ticket_Type'].fillna('Unknown')
dmt_df['Remarks']=dmt_df['Remarks'].fillna('normal')
dmt_df['Passengers']=dmt_df['Passengers'].fillna(0)
dmt_df[['Distance_km','Cost_per_passenger']]=dmt_df[['Distance_km','Cost_per_passenger']].round(2)
display(dmt_df.info())

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[us]
 2   From_Station        10000 non-null  str
 3   To_Station          10000 non-null  str
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          10000 non-null  float64
 8   Ticket_Type         10000 non-null  str
 9   Remarks             10000 non-null  str
dtypes: datetime64[us](1), float64(4), int64(1), str(4)
memory usage: 859.4 KB

None

In [22]:
display(dmt_df.head(100))

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
95,136207,2022-06-12,Rajouri Garden,Chandni Chowk,4.04,95.71,22.34,16.0,Unknown,off-peak
96,22935,2023-11-08,Noida City Centre,Rajouri Garden,5.40,134.64,28.36,23.0,Tourist Card,festival
97,133891,2023-01-24,Noida City Centre,Punjabi Bagh,9.01,40.85,85.30,22.0,Tourist Card,off-peak
98,56198,2023-12-17,Kashmere Gate,Kirti Nagar,1.22,193.09,29.88,15.0,Single,off-peak
99,130665,2022-10-11,Jasola Vihar,Chandni Chowk,11.94,124.48,75.62,16.0,Single,normal

In [23]:
# Convert Date Column into datatime format
dmt_df['Date'] = pd.to_datetime(dmt_df['Date'], errors='coerce')
display(dmt_df.head(100))

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
95,136207,2022-06-12,Rajouri Garden,Chandni Chowk,4.04,95.71,22.34,16.0,Unknown,off-peak
96,22935,2023-11-08,Noida City Centre,Rajouri Garden,5.40,134.64,28.36,23.0,Tourist Card,festival
97,133891,2023-01-24,Noida City Centre,Punjabi Bagh,9.01,40.85,85.30,22.0,Tourist Card,off-peak
98,56198,2023-12-17,Kashmere Gate,Kirti Nagar,1.22,193.09,29.88,15.0,Single,off-peak
99,130665,2022-10-11,Jasola Vihar,Chandni Chowk,11.94,124.48,75.62,16.0,Single,normal

In [24]:
# Format Numeric Columns
dmt_df['Distance_km'] = pd.to_numeric(dmt_df['Distance_km'], errors='coerce')
dmt_df['Fare'] = pd.to_numeric(dmt_df['Fare'], errors='coerce')
dmt_df['Cost_per_passenger'] = pd.to_numeric(dmt_df['Cost_per_passenger'], errors='coerce')
dmt_df['Passengers'] = pd.to_numeric(dmt_df['Passengers'], errors='coerce')
display(dmt_df.head())
dmt_df = dmt_df.drop_duplicates()

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak

In [25]:
display(dmt_df.info())
display(dmt_df.describe())

<class 'pandas.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[us]
 2   From_Station        10000 non-null  str
 3   To_Station          10000 non-null  str
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          10000 non-null  float64
 8   Ticket_Type         10000 non-null  str
 9   Remarks             10000 non-null  str
dtypes: datetime64[us](1), float64(4), int64(1), str(4)
memory usage: 859.4 KB

None

,TripID,Date,Distance_km,Fare,Cost_per_passenger,Passengers
count,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.000000
mean,75119.461100,2023-07-01 16:59:22.560000,5.454417,104.386132,62.899180,19.837800
min,35.000000,2022-01-01 00:00:00,0.500000,10.010000,5.040000,0.000000
25%,38425.000000,2022-10-03 00:00:00,1.900000,56.802500,34.077500,17.000000
50%,74774.500000,2023-07-06 12:00:00,3.930000,104.540000,63.320000,20.000000
75%,112112.500000,2024-03-31 00:00:00,7.330000,150.745000,92.090000,23.000000
max,149984.000000,2024-12-30 00:00:00,45.690000,199.990000,120.000000,37.000000
std,42909.579425,NaN,5.026506,54.789233,33.298324,4.838205

In [26]:
# Save as CSV
dmt_df.to_csv("delhi_metro_trips.csv", index=False)
display("Successfully File saved as .csv extension")

'Successfully File saved as .csv extension'